import type { Archetype } from '../game/combat/types';

const asset = (file: string) => `${import.meta.env.BASE_URL}assets/${file}`;
export const ASSETS = {
  dili_idle: asset('dili-idle.png'),
  skill_packet: asset('skill-packet.png'),
  skill_hammer: asset('skill-hammer.png'),
  skill_firewall: asset('skill-firewall.png'),
  skill_viral: asset('skill-viral.png'),
  skill_rage: asset('skill-rage.png'),
  enemy_spam_bot_idle: asset('spam-bot.svg'),
  enemy_boss_spam_king_idle: asset('spam-king.svg'),
  enemy_boss_loop_phantom_idle: asset('loop-phantom.svg'),
  enemy_boss_raid_master_idle: asset('raid-master.svg'),
  enemy_boss_null_exe_idle: asset('null-exe.svg'),
  music_feed: asset('feed-loop.wav'),
  music_dliclips: asset('dliclips-loop.wav'),
  music_rooms: asset('rooms-loop.wav'),
  music_core: asset('core-loop.wav'),
  sfx_attack: asset('attack.wav'),
  sfx_crit: asset('crit.wav'),
  sfx_ultimate: asset('ultimate.wav'),
  sfx_select: asset('select.wav'),
  sfx_dodge: asset('dodge.wav'),
  sfx_heal: asset('heal.wav'),
  sfx_shield: asset('shield.wav'),
  sfx_death: asset('death.wav'),
  sfx_boss_intro: asset('boss-intro.wav'),
  sfx_victory: asset('victory.wav'),
  sfx_defeat: asset('defeat.wav'),
  sfx_reward: asset('reward.wav'),
  sfx_legendary: asset('legendary.wav'),
  sfx_hammer: asset('hammer.wav'),
  sfx_shield_break: asset('shield-break.wav'),
  sfx_boss_king_attack: asset('boss-king-attack.wav'),
  sfx_boss_phantom_attack: asset('boss-phantom-attack.wav'),
  sfx_boss_raid_attack: asset('boss-raid-attack.wav'),
  sfx_boss_null_attack: asset('boss-null-attack.wav'),
};

export const SKILL_ART: Partial<Record<Archetype, string>> = {
  packet: ASSETS.skill_packet,
  hammer: ASSETS.skill_hammer,
  firewall: ASSETS.skill_firewall,
  viral: ASSETS.skill_viral,
  rage: ASSETS.skill_rage,
};
