import type { Archetype } from '../game/combat/types';

const asset = (file: string) => `${import.meta.env.BASE_URL}assets/${file}`;
export const ASSETS = {
  dili_idle: asset('dili-idle.png'),
  dili_attack: asset('dili-attack.png'),
  dili_hurt: asset('dili-hurt.png'),
  dili_ultimate: asset('dili-ultimate.png'),
  skill_packet: asset('skill-packet.png'),
  skill_hammer: asset('skill-hammer.png'),
  skill_firewall: asset('skill-firewall.png'),
  skill_moderation: asset('skill-moderation.png'),
  skill_encryption: asset('skill-encryption.png'),
  skill_viral: asset('skill-viral.png'),
  skill_rage: asset('skill-rage.png'),
  skill_heal: asset('skill-heal.png'),
  enemy_bot_placeholder: asset('spam-bot.svg'),
  enemy_spam_bot_idle: asset('spam-bot.png'),
  enemy_scam_link_idle: asset('scam-link.png'),
  enemy_bug_idle: asset('bug.png'),
  enemy_raid_bot_idle: asset('raid-bot.png'),
  enemy_fake_account_idle: asset('fake-account.png'),
  enemy_data_leech_idle: asset('data-leech.png'),
  enemy_corrupted_clip_idle: asset('corrupted-clip.png'),
  enemy_toxic_reply_idle: asset('toxic-reply.png'),
  enemy_popup_idle: asset('popup.png'),
  enemy_null_fragment_idle: asset('null-fragment.png'),
  enemy_boss_spam_king_idle: asset('spam-king.svg'),
  enemy_boss_loop_phantom_idle: asset('loop-phantom.svg'),
  enemy_boss_raid_master_idle: asset('raid-master.svg'),
  enemy_boss_null_exe_idle: asset('null-exe.svg'),
  music_feed: asset('feed-loop.wav'),
  music_dliclips: asset('dliclips-loop.wav'),
  music_rooms: asset('rooms-loop.wav'),
  music_core: asset('core-loop.wav'),
  sfx_attack: asset('attack.wav'),
  sfx_crit: asset('crit.wav'),
  sfx_ultimate: asset('ultimate.wav'),
  sfx_select: asset('select.wav'),
  sfx_dodge: asset('dodge.wav'),
  sfx_heal: asset('heal.wav'),
  sfx_shield: asset('shield.wav'),
  sfx_death: asset('death.wav'),
  sfx_boss_intro: asset('boss-intro.wav'),
  sfx_victory: asset('victory.wav'),
  sfx_defeat: asset('defeat.wav'),
  sfx_reward: asset('reward.wav'),
  sfx_legendary: asset('legendary.wav'),
  sfx_hammer: asset('hammer.wav'),
  sfx_shield_break: asset('shield-break.wav'),
  sfx_boss_king_attack: asset('boss-king-attack.wav'),
  sfx_boss_phantom_attack: asset('boss-phantom-attack.wav'),
  sfx_boss_raid_attack: asset('boss-raid-attack.wav'),
  sfx_boss_null_attack: asset('boss-null-attack.wav'),
};

export const SKILL_ART: Record<Archetype, string> = {
  packet: ASSETS.skill_packet,
  hammer: ASSETS.skill_hammer,
  firewall: ASSETS.skill_firewall,
  moderation: ASSETS.skill_moderation,
  encryption: ASSETS.skill_encryption,
  viral: ASSETS.skill_viral,
  rage: ASSETS.skill_rage,
  heal: ASSETS.skill_heal,
};
