import type { Archetype } from '../game/combat/types';

const asset = (file: string) => `${import.meta.env.BASE_URL}assets/${file}`;
export const ASSETS = {
  background_feed_city: asset('background-feed-city.webp'),
  background_dliclip_stream: asset('background-dliclip-stream.webp'),
  background_dili_rooms: asset('background-dili-rooms.webp'),
  background_core_network: asset('background-core-network.webp'),
  dili_idle: asset('dili-idle.png'),
  dili_attack: asset('dili-attack.png'),
  dili_sword_idle: asset('dili-sword-idle.webp'),
  dili_sword_attack: asset('dili-sword-attack.webp'),
  dili_hammer_idle: asset('dili-hammer-idle.webp'),
  dili_hammer_attack: asset('dili-hammer-attack.webp'),
  dili_hurt: asset('dili-hurt.png'),
  dili_ultimate: asset('dili-ultimate.png'),
  skill_packet: asset('skill-packet.png'),
  skill_hammer: asset('skill-hammer.png'),
  skill_firewall: asset('skill-firewall.png'),
  skill_moderation: asset('skill-moderation.png'),
  skill_encryption: asset('skill-encryption.png'),
  skill_viral: asset('skill-viral.png'),
  skill_rage: asset('skill-rage.png'),
  skill_heal: asset('skill-heal.png'),
  chest_gear: asset('chest-gear.webp'),
  chest_skill: asset('chest-skill.webp'),
  enemy_bot_placeholder: asset('spam-bot.svg'),
  enemy_spam_bot_idle: asset('spam-bot.png'),
  enemy_scam_link_idle: asset('scam-link.png'),
  enemy_bug_idle: asset('bug.png'),
  enemy_raid_bot_idle: asset('raid-bot.png'),
  enemy_fake_account_idle: asset('fake-account.png'),
  enemy_data_leech_idle: asset('data-leech.png'),
  enemy_corrupted_clip_idle: asset('corrupted-clip.png'),
  enemy_toxic_reply_idle: asset('toxic-reply.png'),
  enemy_popup_idle: asset('popup.png'),
  enemy_null_fragment_idle: asset('null-fragment.png'),
  enemy_boss_spam_king_idle: asset('spam-king.png'),
  enemy_boss_loop_phantom_idle: asset('loop-phantom.png'),
  enemy_boss_raid_master_idle: asset('raid-master.png'),
  enemy_boss_null_exe_idle: asset('null-exe.png'),
  music_feed: asset('feed-loop.mp3'),
  music_dliclips: asset('dliclips-loop.mp3'),
  music_rooms: asset('rooms-loop.mp3'),
  music_core: asset('core-loop.mp3'),
  sfx_attack: asset('attack.mp3'),
  sfx_crit: asset('crit.mp3'),
  sfx_ultimate: asset('ultimate.mp3'),
  sfx_select: asset('select.mp3'),
  sfx_dodge: asset('dodge.mp3'),
  sfx_heal: asset('heal.mp3'),
  sfx_shield: asset('shield.mp3'),
  sfx_death: asset('death.mp3'),
  sfx_boss_intro: asset('boss-intro.mp3'),
  sfx_victory: asset('victory.mp3'),
  sfx_defeat: asset('defeat.mp3'),
  sfx_reward: asset('reward.mp3'),
  sfx_legendary: asset('legendary.mp3'),
  sfx_hammer: asset('hammer.mp3'),
  sfx_sword: asset('sword.mp3'),
  sfx_shield_break: asset('shield-break.mp3'),
  sfx_boss_king_attack: asset('boss-king-attack.mp3'),
  sfx_boss_phantom_attack: asset('boss-phantom-attack.mp3'),
  sfx_boss_raid_attack: asset('boss-raid-attack.mp3'),
  sfx_boss_null_attack: asset('boss-null-attack.mp3'),
};

export const SKILL_ART: Record<Archetype, string> = {
  packet: ASSETS.skill_packet,
  hammer: ASSETS.skill_hammer,
  firewall: ASSETS.skill_firewall,
  moderation: ASSETS.skill_moderation,
  encryption: ASSETS.skill_encryption,
  viral: ASSETS.skill_viral,
  rage: ASSETS.skill_rage,
  heal: ASSETS.skill_heal,
};
