import type { LucideIcon } from 'lucide-react';
import {
  ArrowDownToLine,
  ArrowUp,
  AudioLines,
  BadgeAlert,
  BadgeCheck,
  Ban,
  Binary,
  Bomb,
  BookOpenCheck,
  Clapperboard,
  CloudLightning,
  CloudUpload,
  CopyPlus,
  Cpu,
  Crosshair,
  Crown,
  DatabaseZap,
  Dna,
  Eraser,
  FastForward,
  Filter,
  Fingerprint,
  Flame,
  Gauge,
  GitBranch,
  Gavel,
  Ghost,
  HandHeart,
  Heart,
  HeartHandshake,
  HeartPulse,
  Infinity,
  KeyRound,
  Layers3,
  LifeBuoy,
  LockKeyhole,
  MessageCircleReply,
  MessageSquareMore,
  MessageSquareWarning,
  Minimize2,
  Network,
  OctagonX,
  PackagePlus,
  Play,
  Radio,
  RadioTower,
  Repeat,
  Repeat2,
  Rocket,
  Route,
  Scale,
  ScanEye,
  ScrollText,
  Share2,
  Shield,
  ShieldBan,
  ShieldEllipsis,
  ShieldPlus,
  ShieldQuestion,
  ShieldCheck,
  Signal,
  Skull,
  Sparkles,
  Sprout,
  Star,
  Swords,
  Target,
  Timer,
  TimerOff,
  TrendingUp,
  UsersRound,
  Wrench,
} from 'lucide-react';

/** Per-skill semantic marks layered over each archetype's original icon art. */
export const SKILL_GLYPHS = {
  packet_boost: ArrowUp,
  double_packet: CopyPlus,
  triple_packet: Layers3,
  viral_packet: Repeat2,
  clean_packet: Eraser,
  packet_compression: Minimize2,
  packet_overflow: ArrowDownToLine,
  infinite_scroll: Infinity,
  sharp_signal: Radio,
  critical_upload: Target,
  clip_on_crit: Clapperboard,
  dliclip_bounce: Play,
  viral_critical: BadgeAlert,
  rapid_feed: Gauge,
  feed_momentum: TrendingUp,
  trending_now: Flame,
  combo_upload: CloudUpload,
  chain_reaction: GitBranch,
  endless_feed: ScrollText,
  auto_reply: MessageCircleReply,
  toxic_reply: MessageSquareWarning,
  reflective_moderation: ShieldEllipsis,
  ratio: Scale,
  last_word: MessageSquareMore,
  ban_hammer: Gavel,
  heavy_ban: ShieldBan,
  mass_ban: Bomb,
  mark_for_review: ScanEye,
  permanent_ban: Ban,
  zero_tolerance: OctagonX,
  firewall: Shield,
  reinforced_firewall: ShieldPlus,
  packet_filter: Filter,
  firewall_pulse: AudioLines,
  emergency_patch: Wrench,
  unbreakable_session: ShieldCheck,
  viral_seed: Sprout,
  repost: Repeat,
  trending_explosion: Sparkles,
  share_count: Share2,
  network_effect: Network,
  auto_mod: BadgeCheck,
  slow_mode: Timer,
  timeout: TimerOff,
  community_notes: BookOpenCheck,
  trust_and_safety: HeartHandshake,
  full_moderation_suite: ShieldQuestion,
  encrypted_session: KeyRound,
  hidden_route: Route,
  private_channel: LockKeyhole,
  zero_knowledge: Binary,
  ghost_packet: Ghost,
  end_to_end: Fingerprint,
  faster_upload: FastForward,
  overclock: Cpu,
  rage_cache: DatabaseZap,
  ultimate_packet_storm: CloudLightning,
  overdrive_shield: RadioTower,
  infinite_bandwidth: Signal,
  recovery_packet: PackagePlus,
  healthy_community: UsersRound,
  lifeline: HeartPulse,
  second_chance: LifeBuoy,
  community_support: HandHeart,
  never_log_off: Heart,
  boss_hunter: Crown,
  elite_cleaner: Swords,
  adaptation: Dna,
  final_push: Rocket,
  main_character_energy: Star,
} satisfies Record<string, LucideIcon>;

export const STATUS_GLYPHS = {
  burn: Flame,
  glitch: Skull,
  vulnerable: Crosshair,
  silence: AudioLines,
  slow: Timer,
  corrupted: DatabaseZap,
  marked: ScanEye,
} satisfies Record<string, LucideIcon>;
