import type {
  Action,
  Archetype,
  Effect,
  Rarity,
  SkillDefinition,
  Stats,
  Trigger,
} from '../game/combat/types';
const mod = (stat: keyof Stats, value: number): Effect => ({ type: 'modifier', stat, value });
const proc = (on: Trigger, action: Action, every = 1, chance = 1, once = false): Effect => ({
  type: 'trigger',
  on,
  action,
  every,
  chance,
  once,
});
const hit = (
  value: number,
  label: string,
  target: 'target' | 'all' | 'strongest' = 'target',
): Action => ({ kind: 'damage', value, label, target });
const rule = (name: Extract<Effect, { type: 'rule' }>['rule'], value = 1): Effect => ({
  type: 'rule',
  rule: name,
  value,
});
const status = (
  id: 'glitch' | 'vulnerable' | 'silence' | 'marked',
  turns = 2,
  value = 0.1,
): Action => ({ kind: 'status', status: id, turns, value });
const levels: Record<Archetype, number> = {
  packet: 1,
  firewall: 1,
  hammer: 2,
  moderation: 4,
  encryption: 5,
  viral: 6,
  rage: 1,
  heal: 1,
};
function skill(
  id: string,
  name: string,
  rarity: Rarity,
  tag: Archetype,
  description: string,
  effects: Effect[],
  prerequisites: string[] = [],
  maxRank = 1,
  unlockLevel = levels[tag],
): SkillDefinition {
  return {
    id,
    name,
    rarity,
    tags: [tag],
    description,
    effects,
    prerequisites,
    maxRank,
    unlockLevel,
  };
}
export const SKILLS: SkillDefinition[] = [
  skill(
    'packet_boost',
    'Packet Boost',
    'common',
    'packet',
    'Basic attack damage +20%. Ranks II / III: +35% / +50%.',
    [mod('basicDamage', 0.2)],
    [],
    3,
  ),
  skill(
    'double_packet',
    'Double Packet',
    'rare',
    'packet',
    'Every basic fires a second packet for 45% ATK.',
    [proc('basic', hit(0.45, 'Double Packet'))],
  ),
  skill(
    'triple_packet',
    'Triple Packet',
    'epic',
    'packet',
    'Add a third packet for 30% ATK.',
    [proc('basic', hit(0.3, 'Triple Packet'))],
    ['double_packet'],
  ),
  skill(
    'viral_packet',
    'Viral Packet',
    'rare',
    'packet',
    'Basics have a 25% chance to repeat at 60% ATK.',
    [proc('basic', hit(0.6, 'Viral Packet'), 1, 0.25)],
  ),
  skill(
    'clean_packet',
    'Clean Packet',
    'common',
    'packet',
    'Basic attacks deal +25% damage to debuffed enemies.',
    [mod('cleanPacket', 0.25)],
  ),
  skill(
    'packet_compression',
    'Packet Compression',
    'rare',
    'packet',
    'Basic damage +35%. Rage per basic −5.',
    [mod('basicDamage', 0.35), mod('ragePerAttack', -5)],
  ),
  skill(
    'packet_overflow',
    'Packet Overflow',
    'epic',
    'packet',
    'Every 5th basic attack hits all enemies.',
    [rule('overflow')],
  ),
  skill(
    'infinite_scroll',
    'Infinite Scroll',
    'legendary',
    'packet',
    'Each Combo adds 5% basic damage this battle, up to 100%.',
    [rule('infinite_scroll')],
  ),
  skill(
    'sharp_signal',
    'Sharp Signal',
    'common',
    'packet',
    'Critical chance +8%.',
    [mod('critRate', 0.08)],
    [],
    1,
    3,
  ),
  skill(
    'critical_upload',
    'Critical Upload',
    'rare',
    'packet',
    'Critical damage +35 percentage points.',
    [mod('critDamage', 0.35)],
    [],
    1,
    3,
  ),
  skill(
    'clip_on_crit',
    'Clip on Crit',
    'rare',
    'packet',
    'Basic critical hits launch a 60% ATK DliClip.',
    [proc('crit', hit(0.6, 'DliClip'))],
    [],
    1,
    3,
  ),
  skill(
    'dliclip_bounce',
    'DliClip Bounce',
    'epic',
    'packet',
    'DliClip bounces to 2 additional enemies.',
    [rule('bounce')],
    ['clip_on_crit'],
    1,
    3,
  ),
  skill(
    'viral_critical',
    'Viral Critical',
    'epic',
    'packet',
    'Critical hits apply +10% Vulnerable for 2 turns.',
    [proc('crit', status('vulnerable'))],
    [],
    1,
    3,
  ),
  skill('rapid_feed', 'Rapid Feed', 'common', 'packet', 'Combo chance +10%.', [
    mod('comboRate', 0.1),
  ]),
  skill(
    'feed_momentum',
    'Feed Momentum',
    'rare',
    'packet',
    'Each Combo in the same turn gains +12% damage.',
    [mod('comboMomentum', 0.12)],
  ),
  skill(
    'trending_now',
    'Trending Now',
    'legendary',
    'packet',
    'Every 3rd critical hit triggers an extra basic attack.',
    [proc('crit', { kind: 'extra_basic', value: 1 }, 3)],
    [],
    1,
    3,
  ),
  skill('combo_upload', 'Combo Upload', 'rare', 'rage', 'Each Combo grants +10 Rage.', [
    proc('combo', { kind: 'rage', value: 10 }),
  ]),
  skill(
    'chain_reaction',
    'Chain Reaction',
    'epic',
    'packet',
    'The third attack in a Combo chain explodes for 100% ATK.',
    [{ type: 'trigger', on: 'combo', comboIndex: 2, action: hit(1, 'Chain Reaction', 'all') }],
  ),
  skill(
    'endless_feed',
    'Endless Feed',
    'legendary',
    'packet',
    'Maximum Combo chain +2. Combo chance +15%.',
    [mod('maxCombo', 2), mod('comboRate', 0.15)],
  ),
  skill('auto_reply', 'Auto Reply', 'common', 'encryption', 'Counter chance +10%.', [
    mod('counterRate', 0.1),
  ]),
  skill(
    'toxic_reply',
    'Toxic Reply',
    'rare',
    'moderation',
    'Counter attacks apply Glitch for 2 turns.',
    [proc('counter', status('glitch'))],
    ['auto_reply'],
  ),
  skill(
    'reflective_moderation',
    'Reflective Moderation',
    'rare',
    'firewall',
    'Each Counter grants 5% max HP Shield.',
    [proc('counter', { kind: 'shield', value: 0.05 })],
  ),
  skill('ratio', 'Ratio', 'epic', 'encryption', 'Counter damage +80% against Vulnerable enemies.', [
    mod('counterDamage', 0.8),
  ]),
  skill(
    'last_word',
    'Last Word',
    'legendary',
    'encryption',
    'First direct hit received each turn guarantees a Counter.',
    [rule('last_word')],
  ),
  skill(
    'ban_hammer',
    'Ban Hammer',
    'common',
    'hammer',
    'Every 4 basic attacks, smash for 140% ATK.',
    [proc('basic', hit(1.4, 'Ban Hammer'), 4)],
  ),
  skill(
    'heavy_ban',
    'Heavy Ban',
    'rare',
    'hammer',
    'Ban Hammer damage +60%.',
    [mod('hammerDamage', 0.6)],
    ['ban_hammer'],
  ),
  skill(
    'mass_ban',
    'Mass Ban',
    'epic',
    'hammer',
    'Ban Hammer deals 70% splash damage to other enemies.',
    [rule('mass_ban')],
    ['ban_hammer'],
  ),
  skill(
    'mark_for_review',
    'Mark for Review',
    'rare',
    'hammer',
    'Basics have 20% chance to Mark for 3 turns.',
    [proc('basic', status('marked', 3), 1, 0.2)],
    ['ban_hammer'],
  ),
  skill(
    'permanent_ban',
    'Permanent Ban',
    'epic',
    'hammer',
    'Ban Hammer consumes Mark for +150% damage.',
    [rule('permanent_ban')],
    ['ban_hammer', 'mark_for_review'],
  ),
  skill(
    'zero_tolerance',
    'Zero Tolerance',
    'legendary',
    'hammer',
    'Hammer executes non-boss enemies below 12% HP.',
    [rule('execute')],
    ['ban_hammer'],
  ),
  skill('firewall', 'Firewall', 'common', 'firewall', 'Every 4 turns, gain 8% max HP Shield.', [
    proc('turn_start', { kind: 'shield', value: 0.08 }, 4),
  ]),
  skill(
    'reinforced_firewall',
    'Reinforced Firewall',
    'rare',
    'firewall',
    'Shield generation +50%.',
    [mod('shieldPower', 0.5)],
    ['firewall'],
  ),
  skill(
    'packet_filter',
    'Packet Filter',
    'rare',
    'firewall',
    'While shielded, incoming damage −15%.',
    [mod('shieldReduction', 0.15)],
  ),
  skill(
    'firewall_pulse',
    'Firewall Pulse',
    'epic',
    'firewall',
    'When Shield breaks, deal 100% ATK to all enemies.',
    [proc('shield_break', hit(1, 'Firewall Pulse', 'all'))],
  ),
  skill(
    'emergency_patch',
    'Emergency Patch',
    'epic',
    'firewall',
    'Below 30% HP, gain 25% max HP Shield once per battle.',
    [proc('low_hp', { kind: 'shield', value: 0.25 }, 1, 1, true)],
  ),
  skill(
    'unbreakable_session',
    'Unbreakable Session',
    'legendary',
    'firewall',
    'Convert 50% excess Shield into healing.',
    [rule('excess_heal')],
  ),
  skill(
    'viral_seed',
    'Viral Seed',
    'common',
    'viral',
    'Kills have 20% chance to explode for 60% ATK.',
    [proc('kill', hit(0.6, 'Viral Explosion', 'all'), 1, 0.2)],
  ),
  skill(
    'repost',
    'Repost',
    'rare',
    'viral',
    'Viral explosions repeat once at 40% damage.',
    [rule('repost')],
    ['viral_seed'],
  ),
  skill(
    'trending_explosion',
    'Trending Explosion',
    'epic',
    'viral',
    'Viral explosion damage +80%.',
    [mod('explosionDamage', 0.8)],
    ['viral_seed'],
  ),
  skill(
    'share_count',
    'Share Count',
    'rare',
    'viral',
    'Each kill adds 3% explosion damage this battle.',
    [rule('share_count')],
    ['viral_seed'],
  ),
  skill(
    'network_effect',
    'Network Effect',
    'legendary',
    'viral',
    'Every 5th damaging skill creates a Viral explosion.',
    [rule('network_effect')],
  ),
  skill(
    'auto_mod',
    'Auto Mod',
    'common',
    'moderation',
    'Every 4 turns, Glitch the strongest enemy.',
    [proc('turn_start', status('glitch'), 4)],
  ),
  skill(
    'slow_mode',
    'Slow Mode',
    'rare',
    'moderation',
    'Glitched enemies deal another 15% less damage.',
    [mod('glitchedReduction', 0.15)],
    ['auto_mod'],
  ),
  skill(
    'timeout',
    'Timeout',
    'rare',
    'moderation',
    'Every 6 turns, Silence a non-boss for 1 turn.',
    [proc('turn_start', status('silence', 1), 6)],
  ),
  skill(
    'community_notes',
    'Community Notes',
    'epic',
    'moderation',
    'Debuffed enemies take +18% damage.',
    [mod('debuffDamage', 0.18)],
  ),
  skill(
    'trust_and_safety',
    'Trust & Safety',
    'epic',
    'moderation',
    'Applying a debuff grants 2% max HP Shield.',
    [proc('debuff', { kind: 'shield', value: 0.02 })],
  ),
  skill(
    'full_moderation_suite',
    'Full Moderation Suite',
    'legendary',
    'moderation',
    'Applying Glitch also applies Vulnerable.',
    [rule('full_moderation')],
  ),
  skill('encrypted_session', 'Encrypted Session', 'common', 'encryption', 'Dodge chance +6%.', [
    mod('dodgeRate', 0.06),
  ]),
  skill(
    'hidden_route',
    'Hidden Route',
    'rare',
    'encryption',
    'After Dodge, next basic gains +20% Crit chance.',
    [proc('dodge', { kind: 'next_crit', value: 0.2 })],
  ),
  skill(
    'private_channel',
    'Private Channel',
    'rare',
    'encryption',
    'After Dodge, heal 2% max HP.',
    [proc('dodge', { kind: 'heal', value: 0.02 })],
  ),
  skill(
    'zero_knowledge',
    'Zero Knowledge',
    'epic',
    'encryption',
    'Automatically dodge the first direct hit each battle.',
    [rule('first_dodge')],
  ),
  skill(
    'ghost_packet',
    'Ghost Packet',
    'epic',
    'encryption',
    'Dodging launches a 90% ATK packet.',
    [proc('dodge', hit(0.9, 'Ghost Packet'))],
  ),
  skill(
    'end_to_end',
    'End-to-End',
    'legendary',
    'encryption',
    'After 3 Dodges, avoid the next direct enemy action.',
    [rule('end_to_end')],
  ),
  skill('faster_upload', 'Faster Upload', 'common', 'rage', 'Rage gain +20%.', [
    mod('rageGain', 0.2),
  ]),
  skill('overclock', 'Overclock', 'rare', 'rage', 'Ultimate damage +40%.', [
    mod('ultimateDamage', 0.4),
  ]),
  skill('rage_cache', 'Rage Cache', 'rare', 'rage', 'Start every battle with 30 Rage.', [
    mod('startRage', 30),
  ]),
  skill(
    'ultimate_packet_storm',
    'Ultimate Packet Storm',
    'epic',
    'rage',
    'Ultimate launches 3 extra 45% ATK packets.',
    [
      proc('ultimate', hit(0.45, 'Overdrive Packet')),
      proc('ultimate', hit(0.45, 'Overdrive Packet')),
      proc('ultimate', hit(0.45, 'Overdrive Packet')),
    ],
  ),
  skill(
    'overdrive_shield',
    'Overdrive Shield',
    'epic',
    'firewall',
    'Casting Ultimate grants 15% max HP Shield.',
    [proc('ultimate', { kind: 'shield', value: 0.15 })],
  ),
  skill(
    'infinite_bandwidth',
    'Infinite Bandwidth',
    'legendary',
    'rage',
    'After Ultimate, basic damage +35% for 3 turns.',
    [rule('bandwidth')],
  ),
  skill(
    'recovery_packet',
    'Recovery Packet',
    'common',
    'heal',
    'Heal 2% max HP after each won battle.',
    [proc('battle_end', { kind: 'heal', value: 0.02 })],
  ),
  skill(
    'healthy_community',
    'Healthy Community',
    'rare',
    'heal',
    'Every 5 kills this battle, heal 3% max HP.',
    [proc('kill', { kind: 'heal', value: 0.03 }, 5)],
  ),
  skill('lifeline', 'Lifeline', 'rare', 'heal', 'Lifesteal +6% of direct damage dealt.', [
    mod('lifesteal', 0.06),
  ]),
  skill(
    'second_chance',
    'Second Chance',
    'epic',
    'heal',
    'Once per run, prevent lethal damage at 1 HP with 15% Shield.',
    [rule('lethal')],
  ),
  skill('community_support', 'Community Support', 'epic', 'heal', 'Healing effects +40%.', [
    mod('healingPower', 0.4),
  ]),
  skill(
    'never_log_off',
    'Never Log Off',
    'legendary',
    'heal',
    'Once per run, revive with 35% HP.',
    [rule('revive')],
  ),
  skill('boss_hunter', 'Boss Hunter', 'rare', 'packet', 'Damage to bosses +20%.', [
    mod('bossDamage', 0.2),
  ]),
  skill('elite_cleaner', 'Elite Cleaner', 'common', 'packet', 'Damage to elites +15%.', [
    mod('eliteDamage', 0.15),
  ]),
  skill(
    'adaptation',
    'Adaptation',
    'epic',
    'packet',
    'After 10 turns against the same enemy, gain +30% damage.',
    [rule('adaptation')],
  ),
  skill('final_push', 'Final Push', 'epic', 'packet', 'Below 25% HP, damage +35%.', [
    rule('final_push'),
  ]),
  skill(
    'main_character_energy',
    'Main Character Energy',
    'legendary',
    'packet',
    'Against bosses: Crit +15%, Dodge +10%, Rage gain +20%.',
    [rule('main_character')],
  ),
];
export const SKILL_BY_ID = Object.fromEntries(SKILLS.map((s) => [s.id, s]));
