import { SKILLS } from '../src/content/skills';
import { EQUIPMENT } from '../src/content/equipment';
import { existsSync } from 'node:fs';
import { validateContent } from '../src/content/validate';
validateContent();
for (const file of [
  'dili-idle.png',
  'dili-attack.png',
  'dili-hurt.png',
  'dili-ultimate.png',
  'skill-packet.png',
  'skill-hammer.png',
  'skill-firewall.png',
  'skill-moderation.png',
  'skill-encryption.png',
  'skill-viral.png',
  'skill-rage.png',
  'skill-heal.png',
  'spam-bot.svg',
  'spam-bot.png',
  'scam-link.png',
  'bug.png',
  'raid-bot.png',
  'fake-account.png',
  'data-leech.png',
  'corrupted-clip.png',
  'toxic-reply.png',
  'popup.png',
  'null-fragment.png',
  'spam-king.svg',
  'loop-phantom.svg',
  'raid-master.svg',
  'null-exe.svg',
  'spam-king.png',
  'loop-phantom.png',
  'raid-master.png',
  'null-exe.png',
  'dliclips-loop.wav',
  'rooms-loop.wav',
  'core-loop.wav',
  'feed-loop.wav',
  'attack.wav',
  'crit.wav',
  'ultimate.wav',
  'select.wav',
  'dodge.wav',
  'heal.wav',
  'shield.wav',
  'death.wav',
  'boss-intro.wav',
  'victory.wav',
  'defeat.wav',
  'reward.wav',
  'legendary.wav',
  'hammer.wav',
  'shield-break.wav',
  'boss-king-attack.wav',
  'boss-phantom-attack.wav',
  'boss-raid-attack.wav',
  'boss-null-attack.wav',
])
  if (!existsSync(`public/assets/${file}`)) throw new Error(`Asset missing: ${file}`);
console.log(
  `Validated ${SKILLS.length} skills, ${EQUIPMENT.length} equipment definitions and all runtime assets.`,
);
